version: '2'
services:
  web:
    image: jegarma/app-rails-5:v1
    shm_size: 128m
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./:/app-rails-5/src"
    env_file: .env
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    depends_on:
      - postgres
    links:
      - postgres:postgres

  postgres:
    image: postgres:9.4
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
