# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4147a1a28ed016f67eb5a8f854a884d6b05a4de4c178d1ec54f3b35efcbe37036924b576859e47aa2e877afeaf7b818f2c87edcc0e7f5145cf4e9cebdeec175b

test:
  secret_key_base: ebb963ac7bad8a028dc839f6d25d2301c734027588e0b556ba2c5cf412a7e36f5ee1dd8858f1de17161eee6b7b799910d0326a247f22ddea186964454e5589db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
